name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r astudentsguide/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build astudentsguide

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "test"
        path: "astudentsguide/_build/html"
        overwrite: true

    # - name: Upload artifact
    #   id: upload-artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ inputs.name }}
    #     path: ${{ runner.temp }}/artifact.tar
    #     retention-days: ${{ inputs.retention-days }}
    #     if-no-files-found: error

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
