name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r astudentsguide/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build astudentsguide

    # DEBUG
    - name: List build directory
      run: ls -R astudentsguide/_build/html

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: "astudentsguide/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
